// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package gosercomp

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB0025f81DecodeGithubComLritaGosercomp(in *jlexer.Lexer, out *EColorGroup) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "colors":
			if in.IsNull() {
				in.Skip()
				out.Colors = nil
			} else {
				in.Delim('[')
				if out.Colors == nil {
					if !in.IsDelim(']') {
						out.Colors = make([]string, 0, 4)
					} else {
						out.Colors = []string{}
					}
				} else {
					out.Colors = (out.Colors)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Colors = append(out.Colors, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0025f81EncodeGithubComLritaGosercomp(out *jwriter.Writer, in EColorGroup) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"id\":")
	out.Int(int(in.Id))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"name\":")
	out.String(string(in.Name))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"colors\":")
	if in.Colors == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in.Colors {
			if v2 > 0 {
				out.RawByte(',')
			}
			out.String(string(v3))
		}
		out.RawByte(']')
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EColorGroup) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0025f81EncodeGithubComLritaGosercomp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EColorGroup) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0025f81EncodeGithubComLritaGosercomp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EColorGroup) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0025f81DecodeGithubComLritaGosercomp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EColorGroup) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0025f81DecodeGithubComLritaGosercomp(l, v)
}
