// Code generated by protoc-gen-go.
// source: protobuf.proto
// DO NOT EDIT!

/*
Package gosercomp is a generated protocol buffer package.

It is generated from these files:
	protobuf.proto

It has these top-level messages:
	ProtoColorGroup
*/
package gosercomp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ProtoColorGroup struct {
	Id               *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Colors           []string `protobuf:"bytes,3,rep,name=colors" json:"colors,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoColorGroup) Reset()         { *m = ProtoColorGroup{} }
func (m *ProtoColorGroup) String() string { return proto.CompactTextString(m) }
func (*ProtoColorGroup) ProtoMessage()    {}

func (m *ProtoColorGroup) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ProtoColorGroup) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ProtoColorGroup) GetColors() []string {
	if m != nil {
		return m.Colors
	}
	return nil
}
